language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t albertedvich/docker-react .

script:
  - docker run -e CI=true albertedvich/docker-react npm run test
