language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t albertedvich/docker-react .

script:
  - docker run -e CI=true albertedvich/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-643825212760"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
